[project]
name = "DiscordBot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "py-cord>=2.6.1",
    "pytz>=2025.2",
    "requests>=2.32.5",
]
